
services:

  headsnet.deploy.convert.markdown:
    class: Headsnet\DeployNotifyBundle\DependencyInjection\ConvertMarkDown

  headsnet.deploy.notify.command:
    class: Headsnet\DeployNotifyBundle\Command\DeployNotifyCommand
    arguments:
      - '@headsnet.deploy.notify.sender'
    tags: ['console.command']

  headsnet.deploy.notify.sender:
    class: Headsnet\DeployNotifyBundle\DependencyInjection\DeployNotifySender
    arguments:
      - '@logger'
      - '@headsnet.deploy_notify.mailer'
      - '@twig'
      - '@headsnet.deploy.convert.markdown'
      - '%kernel.project_dir%'
      - ''

